name: model_from_json
description: A sample command-line application.
version: 1.0.0
homepage: https://github.com/<yourusername>/model_from_json
repository: https://github.com/<yourusername>/model_from_json

environment:
  sdk: ">=3.0.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  equatable: ^2.0.5

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6

executables:
  model_from_json: model_from_json
