name: model_from_json
description: >
  A Dart CLI tool that generates Equatable-ready Dart model classes
  directly from JSON files, with support for nested objects, lists,
  and automatic fromJson/toJson methods.
version: 1.0.1
repository: https://github.com/dipesh-panchal/model_from_json

environment:
  sdk: ">=3.0.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  equatable: ^2.0.5

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6

executables:
  model_from_json: model_from_json
